# Site settings
title: 振振有词
SEOTitle: 振振有词 | BY Gegeliu
header-img: img/post-bg-desk.jpg
email: yoker@163.com
description: "我们真诚了，我们就在真实之中。"
keyword: "BY, BY Gegeliu, C,C++,AI,React,iOS, Apple, iPhone"
url: "http://gegeliu.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blReact,og'
github_repo: "https://github.com/gegeliu/gegeliu.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "我们真诚了，我们就在真实之中!"
sidebar-avatar: /img/avatar_g.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
zhihu_username:     gegeliu
github_username:    gegeliu
#facebook_username:   gegeliu
#jianshu_username:    gegeliu
#twitter_username:    gegeliu




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: gegeliu

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 9120aba864e27daf8edb                          #生成的clientID
  clientSecret: 2d42a43d08e0bda7f57d4c1e8c388429de2fdc21   #生成的clientSecret
  repo: gegeliu.github.io    #仓库名称
  owner: gegeliu    #github用户名
  admin: gegeliu
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "WY",
        href: "http://gezi51.com"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]
